### ISSUE TITLE
Support upstream API enhancements

### ISSUE THREAD

**Issue by ehaupt** [chezou/tdworkflow#17]
There have been some API enhancements in the master branch of digdag: https://github.com/treasure-data/digdag/pull/1697

It would be great if those could be supported in `tdworkflow`

**Comment by chezou** [comment]
@ehaupt Thanks, released 0.7.0. https://github.com/chezou/tdworkflow/releases/tag/v0.7.0

**Comment by chezou** [comment]
Released 0.7.0 https://pypi.org/project/tdworkflow/

**Comment by ehaupt** [comment]
Thank you!
